---
title: "class8_apis"
author: "Robert Kindle"
date: "2026-09-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cincy crashes

```{r api_intro}
httr2::request("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json") |>
  httr2::req_url_query("$limit" = 5) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> cincy_crashes
```

## FRED API key

```{r}
#No need to run this again, ignoring the R environment
Sys.getenv("FRED_API_KEY")   # shows the key, so: Console only
usethis::use_git_ignore(".Renviron")

#This is the generation of the full URL
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json"
  ) |>
  # nothing has been sent yet
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> ohio_jobs # This creates a tangible table in the environment

jobs_df = ohio_jobs[[13]]

# Two options to retrieve only dates in September
# A. Filter rows that I want (not best but works)
jobs_df |>
  dplyr::mutate(
    date = lubridate::ymd(date)
  ) |>
  dplyr::filter(date >= '2026-09-01') -> jobs_df_mod

# B. Use the API
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json",
    observation_start="2026-09-01"
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> ohio_jobs_sept2026

ohio_sept2026_df = ohio_jobs_sept2026$observations
```

## API header example, USA jobs

```{r}
httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_url_query(Keyword = "Data Analyst", ResultsPerPage = 500) |>
  httr2::req_headers(
    Host = "data.usajobs.gov",
    "User-Agent" = "kindlerd@miamioh.edu",
    "Authorization-Key" = Sys.getenv("USAJOBS_API_KEY")
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = TRUE) -> usajobs

usajobs_df = usajobs$SearchResult$SearchResultItems

# Small jobs example in slides
jobs_small = usajobs_df |>
  dplyr::select(
    title = MatchedObjectDescriptor.PositionTitle,
    department = MatchedObjectDescriptor.DepartmentName,
    agency = MatchedObjectDescriptor.OrganizationName,
    location = MatchedObjectDescriptor.PositionLocationDisplay,
    closes = MatchedObjectDescriptor.ApplicationCloseDate
  )

# How many results match "Data Analyst"?
index_datalyst = jobs_small$title |>
  stringr::str_detect(pattern = "Data Analyst|Data Analytics")

jobs_datalyst = jobs_small[index_datalyst, ]
```

